package cnk.air_commercialscalculationengine.settlementrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FOCUpgrades implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String cabinClass;
   private java.lang.String RBD;
   private int numberofUpgrades;
   private double upgradePercentage;
   private java.lang.String fareComponent;

   public FOCUpgrades()
   {
   }

   public java.lang.String getCabinClass()
   {
      return this.cabinClass;
   }

   public void setCabinClass(java.lang.String cabinClass)
   {
      this.cabinClass = cabinClass;
   }

   public java.lang.String getRBD()
   {
      return this.RBD;
   }

   public void setRBD(java.lang.String RBD)
   {
      this.RBD = RBD;
   }

   public int getNumberofUpgrades()
   {
      return this.numberofUpgrades;
   }

   public void setNumberofUpgrades(int numberofUpgrades)
   {
      this.numberofUpgrades = numberofUpgrades;
   }

   public double getUpgradePercentage()
   {
      return this.upgradePercentage;
   }

   public void setUpgradePercentage(double upgradePercentage)
   {
      this.upgradePercentage = upgradePercentage;
   }

   public java.lang.String getFareComponent()
   {
      return this.fareComponent;
   }

   public void setFareComponent(java.lang.String fareComponent)
   {
      this.fareComponent = fareComponent;
   }

   public FOCUpgrades(java.lang.String cabinClass, java.lang.String RBD,
         int numberofUpgrades, double upgradePercentage,
         java.lang.String fareComponent)
   {
      this.cabinClass = cabinClass;
      this.RBD = RBD;
      this.numberofUpgrades = numberofUpgrades;
      this.upgradePercentage = upgradePercentage;
      this.fareComponent = fareComponent;
   }

}