package cnk.air_commercialscalculationengine.settlementrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FreeofCosts implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String contractType;
   private java.lang.String PLBApplicable;
   private java.lang.String commercialType;
   private boolean isApplicable;
   private java.util.List<cnk.air_commercialscalculationengine.settlementrules.SlabDetails> slabDetails;
   private cnk.air_commercialscalculationengine.settlementrules.FOCUtilisation focUtilisation;
   private cnk.air_commercialscalculationengine.settlementrules.FOCTickets focTickets;
   private cnk.air_commercialscalculationengine.settlementrules.FOCUpgrades focUpgrades;

   public FreeofCosts()
   {
   }

   public java.lang.String getContractType()
   {
      return this.contractType;
   }

   public void setContractType(java.lang.String contractType)
   {
      this.contractType = contractType;
   }

   public java.lang.String getPLBApplicable()
   {
      return this.PLBApplicable;
   }

   public void setPLBApplicable(java.lang.String PLBApplicable)
   {
      this.PLBApplicable = PLBApplicable;
   }

   public java.lang.String getCommercialType()
   {
      return this.commercialType;
   }

   public void setCommercialType(java.lang.String commercialType)
   {
      this.commercialType = commercialType;
   }

   public boolean isIsApplicable()
   {
      return this.isApplicable;
   }

   public void setIsApplicable(boolean isApplicable)
   {
      this.isApplicable = isApplicable;
   }

   public java.util.List<cnk.air_commercialscalculationengine.settlementrules.SlabDetails> getSlabDetails()
   {
      return this.slabDetails;
   }

   public void setSlabDetails(
         java.util.List<cnk.air_commercialscalculationengine.settlementrules.SlabDetails> slabDetails)
   {
      this.slabDetails = slabDetails;
   }

   public cnk.air_commercialscalculationengine.settlementrules.FOCUtilisation getFocUtilisation()
   {
      return this.focUtilisation;
   }

   public void setFocUtilisation(
         cnk.air_commercialscalculationengine.settlementrules.FOCUtilisation focUtilisation)
   {
      this.focUtilisation = focUtilisation;
   }

   public cnk.air_commercialscalculationengine.settlementrules.FOCTickets getFocTickets()
   {
      return this.focTickets;
   }

   public void setFocTickets(
         cnk.air_commercialscalculationengine.settlementrules.FOCTickets focTickets)
   {
      this.focTickets = focTickets;
   }

   public cnk.air_commercialscalculationengine.settlementrules.FOCUpgrades getFocUpgrades()
   {
      return this.focUpgrades;
   }

   public void setFocUpgrades(
         cnk.air_commercialscalculationengine.settlementrules.FOCUpgrades focUpgrades)
   {
      this.focUpgrades = focUpgrades;
   }

   public FreeofCosts(
         java.lang.String contractType,
         java.lang.String PLBApplicable,
         java.lang.String commercialType,
         boolean isApplicable,
         java.util.List<cnk.air_commercialscalculationengine.settlementrules.SlabDetails> slabDetails,
         cnk.air_commercialscalculationengine.settlementrules.FOCUtilisation focUtilisation,
         cnk.air_commercialscalculationengine.settlementrules.FOCTickets focTickets,
         cnk.air_commercialscalculationengine.settlementrules.FOCUpgrades focUpgrades)
   {
      this.contractType = contractType;
      this.PLBApplicable = PLBApplicable;
      this.commercialType = commercialType;
      this.isApplicable = isApplicable;
      this.slabDetails = slabDetails;
      this.focUtilisation = focUtilisation;
      this.focTickets = focTickets;
      this.focUpgrades = focUpgrades;
   }

}