package cnk.air_commercialscalculationengine.settlementrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LookToBook implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String contractType;
   private int numberofLooks;
   private int numberofBooks;
   private double commercialAmount;
   private java.lang.String currency;
   private java.lang.String commercialType;
   private boolean isCumulative;
   private boolean isApplicable;
   private int refreshCounter;

   public LookToBook()
   {
   }

   public java.lang.String getContractType()
   {
      return this.contractType;
   }

   public void setContractType(java.lang.String contractType)
   {
      this.contractType = contractType;
   }

   public int getNumberofLooks()
   {
      return this.numberofLooks;
   }

   public void setNumberofLooks(int numberofLooks)
   {
      this.numberofLooks = numberofLooks;
   }

   public int getNumberofBooks()
   {
      return this.numberofBooks;
   }

   public void setNumberofBooks(int numberofBooks)
   {
      this.numberofBooks = numberofBooks;
   }

   public double getCommercialAmount()
   {
      return this.commercialAmount;
   }

   public void setCommercialAmount(double commercialAmount)
   {
      this.commercialAmount = commercialAmount;
   }

   public java.lang.String getCurrency()
   {
      return this.currency;
   }

   public void setCurrency(java.lang.String currency)
   {
      this.currency = currency;
   }

   public java.lang.String getCommercialType()
   {
      return this.commercialType;
   }

   public void setCommercialType(java.lang.String commercialType)
   {
      this.commercialType = commercialType;
   }

   public boolean isIsCumulative()
   {
      return this.isCumulative;
   }

   public void setIsCumulative(boolean isCumulative)
   {
      this.isCumulative = isCumulative;
   }

   public boolean isIsApplicable()
   {
      return this.isApplicable;
   }

   public void setIsApplicable(boolean isApplicable)
   {
      this.isApplicable = isApplicable;
   }

   public int getRefreshCounter()
   {
      return this.refreshCounter;
   }

   public void setRefreshCounter(int refreshCounter)
   {
      this.refreshCounter = refreshCounter;
   }

   public LookToBook(java.lang.String contractType, int numberofLooks,
         int numberofBooks, double commercialAmount,
         java.lang.String currency, java.lang.String commercialType,
         boolean isCumulative, boolean isApplicable, int refreshCounter)
   {
      this.contractType = contractType;
      this.numberofLooks = numberofLooks;
      this.numberofBooks = numberofBooks;
      this.commercialAmount = commercialAmount;
      this.currency = currency;
      this.commercialType = commercialType;
      this.isCumulative = isCumulative;
      this.isApplicable = isApplicable;
      this.refreshCounter = refreshCounter;
   }

}