package cnk.air_commercialscalculationengine.settlementrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MSFFee implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public MSFFee() {
    }

}