package cnk.air_commercialscalculationengine;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Header implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Header() {
    }

}